### ISSUE TITLE
Hardcoded Path

### ISSUE THREAD

**Issue by ProjectInitiative** [Jahfry/Miscellaneous#1]
[line 81](https://github.com/Jahfry/Miscellaneous/blob/main/proxmoxVE71/hookscript-driverctl.pl#L81) contains a hard coded path that does not exist on all systems. 

I suggest either documenting changing this line upon setup, or adding "intelligent" path walking.

**Comment by ProjectInitiative** [comment]
Also, I believe that since this script is only relevant to the node it exists on (i.e. no live migration of GPU/PCI VMs to another node) you can just use "/etc/pve/qemu-server" as the base path instead.

**Comment by Jahfry** [comment]
Thank you! Fixed. Much appreciate the pointer to /etc/pve/qemu-server.
