### ISSUE TITLE
Any updates on the single GPU passthrough in TNS?

### ISSUE THREAD

**Issue by Jah-On** [Jahfry/Miscellaneous#4]
It looks like your guide is out of date for the newer releases as files have moved around. Do you know whether there are any updates from the TrueNAS team about an official solution?

Thanks!

**Comment by Jah-On** [comment]
Ok, I am searching for the specific segments and I will post the updated files here. 
`/usr/share/truenas/webui/609-es2015.f059fa779e0b83eaa150.js` --> `/usr/share/truenas/webui/257-es2015.d63794417c1bb54b4c9b.js`

I will make a pr adding commands to search for the files on each individual's instance.

**Comment by lietu** [comment]
I wrote a script that seems to take care of dynamically finding the relevant files and patching them, as well as doing the other configuration necessary: https://github.com/lietu/truenas-tools/blob/main/truenas-scale-gpu-passthrough-patch.sh

With this I was able to boot a linux VM and give it full access to the system's only GPU including display out capability. Didn't test Windows.

**Comment by iCelo-git** [comment]
I used @lietu script and worked as expected. I cound pass single GPU to my VM. Installed Windows, Windows Update found the driver for my GTX 970. To this point it was promising, but in the end no display output :(

**Comment by lietu** [comment]
Dang, must still be that you need the ROM for Windows, potentially some mitigations to stop Nvidia drivers from detecting that it's in a VM, etc. and from what I understood those customizations are pretty hard to do in TrueNAS Scale.

**Comment by Jah-On** [comment]
> I wrote a script that seems to take care of dynamically finding the relevant files and patching them, as well as doing the other configuration necessary: https://github.com/lietu/truenas-tools/blob/main/truenas-scale-gpu-passthrough-patch.sh
> 
> With this I was able to boot a linux VM and give it full access to the system's only GPU including display out capability. Didn't test Windows.

Thanks! This works great! I can now use my RX 560 for remote gaming, pretty rad.

**Comment by Jahfry** [comment]
@lietu ... thank you, you rock. 

I've been traveling for family issues for months and even if not, I'm not actively using TrueNAS atm so I wouldn't have been able to help. Closing issue.
