### ISSUE TITLE
Miscellaneous/TrueNAS_Scale_driverctl.md -> attaching physical EDID-emulator?

### ISSUE THREAD

**Issue by olebhansen** [Jahfry/Miscellaneous#7]
Question on your TrueNAS Scale GPU endavours... did you at any point attach a physical EDID-emulator to the GPU? I had to do this when doing pass-through on ESXi (to actually get video out over RDP/GeForce NOW stremaing, and not just the GPU connected to the guest OS)...

As an example, not sure this particular device works: https://www.amazon.com/Pass-Through-splitters-Extenders-fit-Headless-3840x2160/dp/B0722NVQHX?th=1

**Comment by Jahfry** [comment]
I have an EDID emulator, but I don't remember using it during my TrueNAS testing. Sorry, been too long.
